/*
* Los identificadores son nombres dados a elementos en un programa como variables, 
  funciones, etc.
    => Las reglas para identificadores son:
    - Los identificadores pueden incluir tanto caracteres como dígitos. Sin embargo,
      el identificador no puede comenzar con un dígito.
    - Los identificadores no pueden incluir símbolos especiales excepto el guión 
      bajo (_) o un signo de dólar ($).
    - Los identificadores no pueden ser palabras clave.
    - Deben ser únicos.
    - Los identificadores distinguen entre mayúsculas y minúsculas.
    - Los identificadores no pueden contener espacios.
    Ejemplo: firstName, first_name, num1, $result
*/

//1. Object Orientation
class Persona {
    origen():void{
        console.log("Hello World !!!");
    }
}
// Llamando al objeto creado
var objPersona = new Persona(); 
objPersona.origen();

//2. Tipos

// Any. Cualquier tipo.

//number, string, boolean, void, null y undefined.

/*  Una variable inicializada con "undefined" significa que la 
    variable no tiene un valor o un objeto asignado, mientras 
    que "null" significa que la variable se ha establecido en un
    objeto cuyo valor no está definido.
*/

//3.Aserción de tipo y scope de variable.

var str = '1' 
var str2:number = <number> <any> str   //str is now of type number 
console.log(str2)

var global_num = 12          //global variable 
class Numbers { 
   num_val = 13;             //class variable 
   static sval = 10;         //static field 
   
   storeNum():void { 
      var local_num = 14;    //local variable 
   } 
} 
console.log("Global num: "+global_num)  
console.log(Numbers.sval)   //static variable  
var obj = new Numbers(); 
console.log("Global num: "+obj.num_val) 

//4. Declaración de variables.

var name2:string = "John"; 
var score1:number = 50;
var score2:number = 42.50
var sum = score1 + score2 
console.log("name"+name) 
console.log("first score: "+score1) 
console.log("second score: "+score2) 
console.log("sum of the scores: "+sum)

//5. Tipo de operador.
//Generated by typescript 1.8.10
var num = 12;
console.log(typeof num);   //output: number

// 6. Funciones.